### ISSUE TITLE
Звисание устройства

### ISSUE THREAD

**Issue by TerAnYu** [klavatron/esp8266-weather#5]
Здравствуйте!
Получилось, наконец-таки, собрать дамп, когда данные перестают передаваться:
```
-->start
WIFI status code: 3
readSensors:        Going to collect data
readSensors:        BMP180
bmp180 pressure     1000.42 hPa
bmp180 temperature  27.00 C
SHT_T:              30.0400009155 C
SHT_H:              32.84 %

Compiled string: ID=MACADDRESSS000000&MACADDRESSS00000001=1000.42&MACADDRESSS00000003=27.00&MACADDRESSS000000BA=32.84&MACADDRESSS000000BB=30.04
=============== send msg start ==============
-------------- host unreachable -------------
reboot in 10 sec
---------------------------------------------

```
После этого устройство более не отвечает, пока не перезапустишь по питанию.

**Comment by klavatron** [comment]
Приветствую! RST через резистор (например 3Ком) подключен на GPIO16?

**Comment by TerAnYu** [comment]
Спасибо!
Был не в курсе такого нюанса и в вашей документации тоже не написано.
В моём случае помогла только перемычка (между RST и D0).

**Comment by klavatron** [comment]
Надо добавить в описание этот нюанс. Дело в том, что при использовании "спящего режима", а он там использовался, чтобы ESP8862 нормально проснулась, надо ногу RST подключать к WAKE (GPIO16 она же D0). Вместо перемычки, всё же лучше подобрать резистор.
